In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('IRIS.csv')

In [5]:
df.head(5)

   sepal_length  sepal_width  petal_length  petal_width            class
0           5.1          3.5           1.4          0.2      Iris-setosa
1           5.6          2.5           3.9          1.1  Iris-versicolor
2           5.9          3.2           4.8          1.8  Iris-versicolor
3           6.1          2.8           4.0          1.3  Iris-versicolor
4           4.6          3.2           1.4          0.2      Iris-setosa

In [6]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class'], dtype='object')

In [7]:
df['petal_length'].dtypes

dtype('float64')

In [8]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
class            object
dtype: object

In [12]:
df.shape

(150, 5)

In [13]:
df.size

750

In [14]:
df.axes

[RangeIndex(start=0, stop=150, step=1),
 Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class'], dtype='object')]

In [15]:
df.values

array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [5.6, 2.5, 3.9, 1.1, 'Iris-versicolor'],
       [5.9, 3.2, 4.8, 1.8, 'Iris-versicolor'],
       [6.1, 2.8, 4.0, 1.3, 'Iris-versicolor'],
       [4.6, 3.2, 1.4, 0.2, 'Iris-setosa'],
       [5.3, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [6.4, 3.2, 5.3, 2.3, 'Iris-virginica'],
       [6.5, 3.0, 5.5, 1.8, 'Iris-virginica'],
       [7.2, 3.2, 6.0, 1.8, 'Iris-virginica'],
       [6.2, 2.8, 4.8, 1.8, 'Iris-virginica'],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Iris-setosaa'],
       [6.5, 3.0, 5.2, 2.0, 'Iris-virginica'],
       [6.2, 3.4, 5.4, 2.3, 'Iris-virginica'],
       [5.9, 3.0, 5.1, 1.8, 'Iris-virginica'],
       [6.2, 2.2, 4.5, 1.5, 'Iris-versicolor'],
       [5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [6.9, 3.1, 5.4, 2.1, 'Iris-virginica'],
       [6.7, 3.1, 5.6, 2.4, 'Iris-virginica'],
       [4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setos'],
       [6.7, 3.3, 5.7, 2.5, 'Iris-virginica'],
       [6.7, 3.0, 5.2, 2.3, 'Iris-virginica'],
       [6.3, 2.5, 5.0, 1.9, 'Iris-virginica'],
       [5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [4.8, 3.4, 1.9, 0.2, 'Iris-setosa'],
       [5.0, 3.0, 1.6, 0.2, 'Iris-setosa'],
       [6.4, 2.9, 4.3, 1.3, 'Iris-versicolor'],
       [6.6, 3.0, 4.4, 1.4, 'Iris-versicolor'],
       [6.8, 2.8, 4.8, 1.4, 'Iris-versicolor'],
       [5.7, 2.5, 5.0, 2.0, 'Iris-virginica'],
       [5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Iris-setosa'],
       [5.1, 3.3, 1.7, 0.5, 'Iris-setosa'],
       [6.1, 2.9, 4.7, 1.4, 'Iris-versicolor'],
       [5.2, 4.1, 1.5, 0.1, 'Iris-setosa'],
       [5.5, 4.2, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [7.7, 3.8, 6.7, 2.2, 'Iris-virginica'],
       [7.7, 2.6, 6.9, 2.3, 'Iris-virginica'],
       [6.0, 2.2, 5.0, 1.5, 'Iris-virginica'],
       [6.9, 3.2, 5.7, 2.3, 'Iris-virginica'],
       [5.6, 2.8, 4.9, 2.0, 'Iris-virginica'],
       [7.7, 2.8, 6.7, 2.0, 'Iris-virginica'],
       [6.3, 2.7, 4.9, 1.8, 'Iris-virginica'],
       [6.7, 3.3, 5.7, 2.1, 'Iris-virginica'],
       [5.0, 3.2, 1.2, 0.2, 'Iris-setosa'],
       [5.5, 3.5, 1.3, 0.2, 'Iris-setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [5.8, 2.7, 5.1, 1.9, 'Iris-virginica'],
       [7.1, 3.0, 5.9, 2.1, 'Iris-virginica'],
       [6.3, 2.9, 5.6, 1.8, 'Iris-virginica'],
       [6.5, 3.0, 5.8, 2.2, 'Iris-virginica'],
       [4.4, 3.0, 1.3, 0.2, 'Iris-setosa'],
       [5.1, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [6.0, 3.4, 4.5, 1.6, 'Iris-versicolor'],
       [6.7, 3.1, 4.7, 1.5, 'Iris-versicolor'],
       [4.8, 3.0, 1.4, 0.3, 'Iris-setosa'],
       [5.1, 3.8, 1.6, 0.2, 'Iris-setosa'],
       [6.9, 3.1, 4.9, 1.5, 'Iris-versicolor'],
       [5.5, 2.3, 4.0, 1.3, 'Iris-versicolor'],
       [6.5, 2.8, 4.6, 1.5, 'Iris-versicolor'],
       [5.7, 2.8, 4.5, 1.3, 'Iris-versicolor'],
       [7.2, 3.0, 5.8, 1.6, 'Iris-virginica'],
       [7.4, 2.8, 6.1, 1.9, 'Iris-virginica'],
       [7.9, 3.8, 6.4, 2.0, 'Iris-virginica'],
       [6.4, 2.8, 5.6, 2.2, 'Iris-virginica'],
       [6.3, 2.8, 5.1, 1.5, 'Iris-virginica'],
       [6.1, 2.6, 5.6, 1.4, 'Iris-virginica'],
       [7.7, 3.0, 6.1, 2.3, 'Iris-virginica'],
       [6.3, 3.3, 4.7, 1.6, 'Iris-versicolor'],
       [4.9, 2.4, 3.3, 1.0, 'Iris-versicolor'],
       [6.6, 2.9, 4.6, 1.3, 'Iris-versicolor'],
       [5.2, 2.7, 3.9, 1.4, 'Iris-versicolor'],
       [5.0, 2.0, 3.5, 1.0, 'Iris-versicolor'],
       [5.9, 3.0, 4.2, 1.5, 'Iris-versicolor'],
       [6.0, 2.2, 4.0, 1.0, 'Iris-versicolor'],
       [5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [6.7, 3.0, 5.0, 1.7, 'Iris-versicolor'],
       [6.0, 2.9, 4.5, 1.5, 'Iris-versicolor'],
       [5.7, 2.6, 3.5, 1.0, 'Iris-versicolor'],
       [5.5, 2.4, 3.8, 1.1, 'Iris-versicolor'],
       [5.5, 2.4, 3.7, 1.0, 'Iris-versicolor'],
       [5.8, 2.7, 3.9, 1.2, 'Iris-versicolor'],
       [5.0, 3.4, 1.6, 0.4, 'Iris-setosa'],
       [5.2, 3.5, 1.5, 0.2, 'Iris-setosa'],
       [6.7, 3.1, 4.4, 1.4, 'Iris-versicolor'],
       [5.6, 3.0, 4.5, 1.5, 'Iris-versicolor'],
       [5.8, 2.8, 5.1, 2.4, 'Iris-virginica'],
       [6.1, 3.0, 4.9, 1.8, 'Iris-virginica'],
       [6.4, 2.8, 5.6, 2.1, 'Iris-virginica'],
       [6.3, 3.4, 5.6, 2.4, 'Iris-virginica'],
       [5.2, 3.4, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.6, 0.2, 'Iris-setosa'],
       [4.8, 3.1, 1.6, 0.2, 'Iris-setosa'],
       [5.4, 3.4, 1.5, 0.4, 'Iris-setosa'],
       [6.0, 2.7, 5.1, 1.6, 'Iris-versicolor'],
       [6.9, 3.1, 5.1, 2.3, 'Iris-virginica'],
       [5.8, 2.7, 5.1, 1.9, 'Iris-virginica'],
       [6.8, 3.2, 5.9, 2.3, 'Iris-virginica'],
       [5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [5.4, 3.0, 4.5, 1.5, 'Iris-versicolor'],
       [5.5, 2.6, 4.4, 1.2, 'Iris-versicolor'],
       [6.1, 3.0, 4.6, 1.4, 'Iris-versicolor'],
       [5.8, 2.6, 4.0, 1.2, 'Iris-versicolor'],
       [6.2, 2.9, 4.3, 1.3, 'Iris-versicolor'],
       [5.1, 2.5, 3.0, 1.1, 'Iris-versicolor'],
       [5.7, 2.8, 4.1, 1.3, 'Iris-versicolor'],
       [6.3, 3.3, 6.0, 2.5, 'Iris-virginica'],
       [7.6, 3.0, 6.6, 2.1, 'Iris-virginica'],
       [4.9, 2.5, 4.5, 1.7, 'Iris-virginica'],
       [7.3, 2.9, 6.3, 1.8, 'Iris-virginica'],
       [6.3, 2.3, 4.4, 1.3, 'Iris-versicolor'],
       [5.6, 3.0, 4.1, 1.3, 'Iris-versicolor'],
       [5.5, 2.5, 4.0, 1.3, 'Iris-versicolor'],
       [5.0, 3.5, 1.3, 0.3, 'Iris-setosa'],
       [4.5, 2.3, 1.3, 0.3, 'Iris-setosa'],
       [4.4, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [5.0, 3.5, 1.6, 0.6, 'Iris-setosa'],
       [5.1, 3.8, 1.9, 0.4, 'Iris-setosa'],
       [6.7, 2.5, 5.8, 1.8, 'Iris-virginica'],
       [7.2, 3.6, 6.1, 2.5, 'Iris-virginica'],
       [6.5, 3.2, 5.1, 2.0, 'Iris-virginica'],
       [5.0, 2.3, 3.3, 1.0, 'Iris-versicolor'],
       [5.6, 2.7, 4.2, 1.3, 'Iris-versicolor'],
       [5.7, 3.0, 4.2, 1.2, 'Iris-versicolor'],
       [5.7, 2.9, 4.2, 1.3, 'Iris-versicolor'],
       [6.4, 2.7, 5.3, 1.9, 'Iris-virginica'],
       [6.8, 3.0, 5.5, 2.1, 'Iris-virginica'],
       [5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [5.8, 2.7, 4.1, 1.0, 'Iris-versicolor'],
       [6.3, 2.5, 4.9, 1.5, 'Iris-versicolor'],
       [6.1, 2.8, 4.7, 1.2, 'Iris-versicolor'],
       [5.6, 2.9, 3.6, 1.3, 'Iris-versicolor'],
       [6.4, 3.1, 5.5, 1.8, 'Iris-virginica'],
       [6.0, 3.0, 4.8, 1.8, 'Iris-virginica'],
       [5.0, 3.3, 1.4, 0.2, 'Iris-setosa'],
       [7.0, 3.2, 4.7, 1.4, 'Iris-versicolor'],
       [6.4, 3.2, 4.5, 1.5, 'Iris-versicolor']], dtype=object)

In [16]:
df.rows

AttributeError: 'DataFrame' object has no attribute 'rows'

In [17]:
df.min()

sepal_length           4.3
sepal_width              2
petal_length             1
petal_width            0.1
class           Iris-setos
dtype: object

In [18]:
df.max()

sepal_length               7.9
sepal_width                4.4
petal_length               6.9
petal_width                2.5
class           Iris-virginica
dtype: object

In [19]:
df.mean()

sepal_length    5.843333
sepal_width     3.054000
petal_length    3.758667
petal_width     1.198667
dtype: float64

In [20]:
df.median()

sepal_length    5.80
sepal_width     3.00
petal_length    4.35
petal_width     1.30
dtype: float64

In [21]:
df.std()

sepal_length    0.828066
sepal_width     0.433594
petal_length    1.764420
petal_width     0.763161
dtype: float64

In [24]:
df.head(5)

   sepal_length  sepal_width  petal_length  petal_width            class
0           5.1          3.5           1.4          0.2      Iris-setosa
1           5.6          2.5           3.9          1.1  Iris-versicolor
2           5.9          3.2           4.8          1.8  Iris-versicolor
3           6.1          2.8           4.0          1.3  Iris-versicolor
4           4.6          3.2           1.4          0.2      Iris-setosa

In [25]:
df.tail(5)

     sepal_length  sepal_width  petal_length  petal_width            class
145           6.4          3.1           5.5          1.8   Iris-virginica
146           6.0          3.0           4.8          1.8   Iris-virginica
147           5.0          3.3           1.4          0.2      Iris-setosa
148           7.0          3.2           4.7          1.4  Iris-versicolor
149           6.4          3.2           4.5          1.5  Iris-versicolor

In [26]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [27]:
df.sample(5)

     sepal_length  sepal_width  petal_length  petal_width            class
24            4.9          3.1           1.5          0.1      Iris-setosa
119           4.9          2.5           4.5          1.7   Iris-virginica
111           5.5          2.6           4.4          1.2  Iris-versicolor
16            5.4          3.7           1.5          0.2      Iris-setosa
83            6.0          2.2           4.0          1.0  Iris-versicolor

In [28]:
df.dropna()

     sepal_length  sepal_width  petal_length  petal_width            class
0             5.1          3.5           1.4          0.2      Iris-setosa
1             5.6          2.5           3.9          1.1  Iris-versicolor
2             5.9          3.2           4.8          1.8  Iris-versicolor
3             6.1          2.8           4.0          1.3  Iris-versicolor
4             4.6          3.2           1.4          0.2      Iris-setosa
5             5.3          3.7           1.5          0.2      Iris-setosa
6             6.4          3.2           5.3          2.3   Iris-virginica
7             6.5          3.0           5.5          1.8   Iris-virginica
8             7.2          3.2           6.0          1.8   Iris-virginica
9             6.2          2.8           4.8          1.8   Iris-virginica
10            4.6          3.1           1.5          0.2      Iris-setosa
11            5.0          3.6           1.4          0.2     Iris-setosaa
12            6.5          3.0           5.2          2.0   Iris-virginica
13            6.2          3.4           5.4          2.3   Iris-virginica
14            5.9          3.0           5.1          1.8   Iris-virginica
15            6.2          2.2           4.5          1.5  Iris-versicolor
16            5.4          3.7           1.5          0.2      Iris-setosa
17            4.8          3.4           1.6          0.2      Iris-setosa
18            4.8          3.0           1.4          0.1      Iris-setosa
19            4.3          3.0           1.1          0.1      Iris-setosa
20            5.8          4.0           1.2          0.2      Iris-setosa
21            6.9          3.1           5.4          2.1   Iris-virginica
22            6.7          3.1           5.6          2.4   Iris-virginica
23            4.4          2.9           1.4          0.2      Iris-setosa
24            4.9          3.1           1.5          0.1      Iris-setosa
25            4.9          3.0           1.4          0.2      Iris-setosa
26            4.7          3.2           1.3          0.2       Iris-setos
27            6.7          3.3           5.7          2.5   Iris-virginica
28            6.7          3.0           5.2          2.3   Iris-virginica
29            6.3          2.5           5.0          1.9   Iris-virginica
..            ...          ...           ...          ...              ...
120           7.3          2.9           6.3          1.8   Iris-virginica
121           6.3          2.3           4.4          1.3  Iris-versicolor
122           5.6          3.0           4.1          1.3  Iris-versicolor
123           5.5          2.5           4.0          1.3  Iris-versicolor
124           5.0          3.5           1.3          0.3      Iris-setosa
125           4.5          2.3           1.3          0.3      Iris-setosa
126           4.4          3.2           1.3          0.2      Iris-setosa
127           5.0          3.5           1.6          0.6      Iris-setosa
128           5.1          3.8           1.9          0.4      Iris-setosa
129           6.7          2.5           5.8          1.8   Iris-virginica
130           7.2          3.6           6.1          2.5   Iris-virginica
131           6.5          3.2           5.1          2.0   Iris-virginica
132           5.0          2.3           3.3          1.0  Iris-versicolor
133           5.6          2.7           4.2          1.3  Iris-versicolor
134           5.7          3.0           4.2          1.2  Iris-versicolor
135           5.7          2.9           4.2          1.3  Iris-versicolor
136           6.4          2.7           5.3          1.9   Iris-virginica
137           6.8          3.0           5.5          2.1   Iris-virginica
138           5.7          3.8           1.7          0.3      Iris-setosa
139           5.1          3.8           1.5          0.3      Iris-setosa
140           5.4          3.4           1.7          0.2      Iris-setosa
141           5.8          2.7           4.1          1.0  Iris-versicolor
142           6.3          2.5           4.9          1.5  Iris-versicolor
143           6.1          2.8           4.7          1.2  Iris-versicolor
144           5.6          2.9           3.6          1.3  Iris-versicolor
145           6.4          3.1           5.5          1.8   Iris-virginica
146           6.0          3.0           4.8          1.8   Iris-virginica
147           5.0          3.3           1.4          0.2      Iris-setosa
148           7.0          3.2           4.7          1.4  Iris-versicolor
149           6.4          3.2           4.5          1.5  Iris-versicolor

[150 rows x 5 columns]

In [29]:
df.head(50).mean()

sepal_length    5.748
sepal_width     3.182
petal_length    3.366
petal_width     1.074
dtype: float64

In [30]:
df.mean()

sepal_length    5.843333
sepal_width     3.054000
petal_length    3.758667
petal_width     1.198667
dtype: float64

In [31]:
df['sepal_length'].describe()

count    150.000000
mean       5.843333
std        0.828066
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max        7.900000
Name: sepal_length, dtype: float64

In [32]:
df.sepal_length.describe()

count    150.000000
mean       5.843333
std        0.828066
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max        7.900000
Name: sepal_length, dtype: float64

In [33]:
df.sepal_length.count()

150

In [36]:
df.sepal_length.mean()

5.843333333333334

In [37]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class'], dtype='object')

In [39]:
df[['sepal_length','sepal_width']]

     sepal_length  sepal_width
0             5.1          3.5
1             5.6          2.5
2             5.9          3.2
3             6.1          2.8
4             4.6          3.2
5             5.3          3.7
6             6.4          3.2
7             6.5          3.0
8             7.2          3.2
9             6.2          2.8
10            4.6          3.1
11            5.0          3.6
12            6.5          3.0
13            6.2          3.4
14            5.9          3.0
15            6.2          2.2
16            5.4          3.7
17            4.8          3.4
18            4.8          3.0
19            4.3          3.0
20            5.8          4.0
21            6.9          3.1
22            6.7          3.1
23            4.4          2.9
24            4.9          3.1
25            4.9          3.0
26            4.7          3.2
27            6.7          3.3
28            6.7          3.0
29            6.3          2.5
..            ...          ...
120           7.3          2.9
121           6.3          2.3
122           5.6          3.0
123           5.5          2.5
124           5.0          3.5
125           4.5          2.3
126           4.4          3.2
127           5.0          3.5
128           5.1          3.8
129           6.7          2.5
130           7.2          3.6
131           6.5          3.2
132           5.0          2.3
133           5.6          2.7
134           5.7          3.0
135           5.7          2.9
136           6.4          2.7
137           6.8          3.0
138           5.7          3.8
139           5.1          3.8
140           5.4          3.4
141           5.8          2.7
142           6.3          2.5
143           6.1          2.8
144           5.6          2.9
145           6.4          3.1
146           6.0          3.0
147           5.0          3.3
148           7.0          3.2
149           6.4          3.2

[150 rows x 2 columns]

In [41]:
df[10:20][['sepal_length','sepal_width']]

    sepal_length  sepal_width
10           4.6          3.1
11           5.0          3.6
12           6.5          3.0
13           6.2          3.4
14           5.9          3.0
15           6.2          2.2
16           5.4          3.7
17           4.8          3.4
18           4.8          3.0
19           4.3          3.0

In [48]:
df.loc[10:20,['sepal_length','sepal_width']]

    sepal_length  sepal_width
10           4.6          3.1
11           5.0          3.6
12           6.5          3.0
13           6.2          3.4
14           5.9          3.0
15           6.2          2.2
16           5.4          3.7
17           4.8          3.4
18           4.8          3.0
19           4.3          3.0
20           5.8          4.0

In [47]:
df.iloc[10:20,[0,1,2,3,4]]

    sepal_length  sepal_width  petal_length  petal_width            class
10           4.6          3.1           1.5          0.2      Iris-setosa
11           5.0          3.6           1.4          0.2     Iris-setosaa
12           6.5          3.0           5.2          2.0   Iris-virginica
13           6.2          3.4           5.4          2.3   Iris-virginica
14           5.9          3.0           5.1          1.8   Iris-virginica
15           6.2          2.2           4.5          1.5  Iris-versicolor
16           5.4          3.7           1.5          0.2      Iris-setosa
17           4.8          3.4           1.6          0.2      Iris-setosa
18           4.8          3.0           1.4          0.1      Iris-setosa
19           4.3          3.0           1.1          0.1      Iris-setosa

In [49]:
zdf=pd.read_csv('zoo.csv')

In [50]:
zdf.head(5)

,animal_name,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tail,domestic,catsize,class
0,aardvark,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
1,antelope,1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,1,1
2,bass,0,0,1,0,0,1,1,1,1,0,0,1,0,1,0,0,4
3,bear,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
4,boar,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1,1

In [51]:
zdf.dtypes

animal_name    object
hair            int64
feathers        int64
eggs            int64
milk            int64
airborne        int64
aquatic         int64
predator        int64
toothed         int64
backbone        int64
breathes        int64
venomous        int64
fins            int64
legs            int64
tail            int64
domestic        int64
catsize         int64
class           int64
dtype: object

In [52]:
zdf[zdf.isnull().any(axis=1)].head()

Empty DataFrame
Columns: [animal_name, hair, feathers, eggs, milk, airborne, aquatic, predator, toothed, backbone, breathes, venomous, fins, legs, tail, domestic, catsize, class]
Index: []

In [53]:
flights=pd.read_csv("ttp://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv""http://rcs.bu.edu/examples/python/data_analysis/flights.csv"")

SyntaxError: EOL while scanning string literal (<ipython-input-53-1dff69077542>, line 1)

In [54]:
dt=pd.read_csv("http://rcs.bu.edu/examples/python/data_analysis/flights.csv")

In [58]:
dt.head()

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
0,2013,1,1,517.0,2.0,830.0,11.0,UA,N14228,1545,EWR,IAH,227.0,1400,5.0,17.0
1,2013,1,1,533.0,4.0,850.0,20.0,UA,N24211,1714,LGA,IAH,227.0,1416,5.0,33.0
2,2013,1,1,542.0,2.0,923.0,33.0,AA,N619AA,1141,JFK,MIA,160.0,1089,5.0,42.0
3,2013,1,1,554.0,-6.0,812.0,-25.0,DL,N668DN,461,LGA,ATL,116.0,762,5.0,54.0
4,2013,1,1,554.0,-4.0,740.0,12.0,UA,N39463,1696,EWR,ORD,150.0,719,5.0,54.0

In [59]:
dt.dtypes

year           int64
month          int64
day            int64
dep_time     float64
dep_delay    float64
arr_time     float64
arr_delay    float64
carrier       object
tailnum       object
flight         int64
origin        object
dest          object
air_time     float64
distance       int64
hour         float64
minute       float64
dtype: object

In [60]:
dt.axes

[RangeIndex(start=0, stop=160754, step=1),
 Index(['year', 'month', 'day', 'dep_time', 'dep_delay', 'arr_time',
        'arr_delay', 'carrier', 'tailnum', 'flight', 'origin', 'dest',
        'air_time', 'distance', 'hour', 'minute'],
       dtype='object')]

In [61]:
dt.columns

Index(['year', 'month', 'day', 'dep_time', 'dep_delay', 'arr_time',
       'arr_delay', 'carrier', 'tailnum', 'flight', 'origin', 'dest',
       'air_time', 'distance', 'hour', 'minute'],
      dtype='object')

In [62]:
dt[dt.isnull().any(axis=1)].head()

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
330,2013,1,1,1807.0,29.0,2251.0,NaN,UA,N31412,1228,EWR,SAN,NaN,2425,18.0,7.0
403,2013,1,1,NaN,NaN,NaN,NaN,AA,N3EHAA,791,LGA,DFW,NaN,1389,NaN,NaN
404,2013,1,1,NaN,NaN,NaN,NaN,AA,N3EVAA,1925,LGA,MIA,NaN,1096,NaN,NaN
855,2013,1,2,2145.0,16.0,NaN,NaN,UA,N12221,1299,EWR,RSW,NaN,1068,21.0,45.0
858,2013,1,2,NaN,NaN,NaN,NaN,AA,NaN,133,JFK,LAX,NaN,2475,NaN,NaN

In [70]:
dt[dt.isnull().any(axis=1)].head()

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
330,2013,1,1,1807.0,29.0,2251.0,NaN,UA,N31412,1228,EWR,SAN,NaN,2425,18.0,7.0
403,2013,1,1,NaN,NaN,NaN,NaN,AA,N3EHAA,791,LGA,DFW,NaN,1389,NaN,NaN
404,2013,1,1,NaN,NaN,NaN,NaN,AA,N3EVAA,1925,LGA,MIA,NaN,1096,NaN,NaN
855,2013,1,2,2145.0,16.0,NaN,NaN,UA,N12221,1299,EWR,RSW,NaN,1068,21.0,45.0
858,2013,1,2,NaN,NaN,NaN,NaN,AA,NaN,133,JFK,LAX,NaN,2475,NaN,NaN

In [71]:
dt.head(331)

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
0,2013,1,1,517.0,2.0,830.0,11.0,UA,N14228,1545,EWR,IAH,227.0,1400,5.0,17.0
1,2013,1,1,533.0,4.0,850.0,20.0,UA,N24211,1714,LGA,IAH,227.0,1416,5.0,33.0
2,2013,1,1,542.0,2.0,923.0,33.0,AA,N619AA,1141,JFK,MIA,160.0,1089,5.0,42.0
3,2013,1,1,554.0,-6.0,812.0,-25.0,DL,N668DN,461,LGA,ATL,116.0,762,5.0,54.0
4,2013,1,1,554.0,-4.0,740.0,12.0,UA,N39463,1696,EWR,ORD,150.0,719,5.0,54.0
5,2013,1,1,558.0,-2.0,753.0,8.0,AA,N3ALAA,301,LGA,ORD,138.0,733,5.0,58.0
6,2013,1,1,558.0,-2.0,924.0,7.0,UA,N29129,194,JFK,LAX,345.0,2475,5.0,58.0
7,2013,1,1,558.0,-2.0,923.0,-14.0,UA,N53441,1124,EWR,SFO,361.0,2565,5.0,58.0
8,2013,1,1,559.0,-1.0,941.0,31.0,AA,N3DUAA,707,LGA,DFW,257.0,1389,5.0,59.0
9,2013,1,1,559.0,-1.0,854.0,-8.0,UA,N76515,1187,EWR,LAS,337.0,2227,5.0,59.0
10,2013,1,1,602.0,-8.0,812.0,-8.0,DL,N971DL,1919,LGA,MSP,170.0,1020,6.0,2.0
11,2013,1,1,606.0,-4.0,858.0,-12.0,AA,N633AA,1895,EWR,MIA,152.0,1085,6.0,6.0
12,2013,1,1,606.0,-4.0,837.0,-8.0,DL,N3739P,1743,JFK,ATL,128.0,760,6.0,6.0
13,2013,1,1,607.0,0.0,858.0,-17.0,UA,N53442,1077,EWR,MIA,157.0,1085,6.0,7.0
14,2013,1,1,611.0,11.0,945.0,14.0,UA,N532UA,303,JFK,SFO,366.0,2586,6.0,11.0
15,2013,1,1,615.0,0.0,833.0,-9.0,DL,N326NB,575,EWR,ATL,120.0,746,6.0,15.0
16,2013,1,1,622.0,-8.0,1017.0,3.0,US,N807AW,245,EWR,PHX,342.0,2133,6.0,22.0
17,2013,1,1,623.0,13.0,920.0,5.0,AA,N3EMAA,1837,LGA,MIA,153.0,1096,6.0,23.0
18,2013,1,1,623.0,-4.0,933.0,1.0,UA,N459UA,496,LGA,IAH,229.0,1416,6.0,23.0
19,2013,1,1,627.0,-3.0,1018.0,0.0,US,N535UW,27,JFK,PHX,330.0,2153,6.0,27.0
20,2013,1,1,628.0,-2.0,1137.0,-3.0,AA,N3BAAA,413,JFK,SJU,192.0,1598,6.0,28.0
21,2013,1,1,628.0,-2.0,1016.0,29.0,UA,N33289,1665,EWR,LAX,366.0,2454,6.0,28.0
22,2013,1,1,629.0,-1.0,824.0,14.0,AA,N3CYAA,303,LGA,ORD,140.0,733,6.0,29.0
23,2013,1,1,629.0,-1.0,824.0,-9.0,US,N426US,1019,EWR,CLT,91.0,529,6.0,29.0
24,2013,1,1,635.0,0.0,1028.0,48.0,AA,N3GKAA,711,LGA,DFW,248.0,1389,6.0,35.0
25,2013,1,1,643.0,-3.0,922.0,-18.0,UA,N497UA,556,EWR,PBI,146.0,1023,6.0,43.0
26,2013,1,1,643.0,-2.0,837.0,-11.0,US,N178US,926,EWR,CLT,91.0,529,6.0,43.0
27,2013,1,1,644.0,8.0,931.0,-9.0,UA,N75435,1701,EWR,FLL,151.0,1065,6.0,44.0
28,2013,1,1,646.0,1.0,910.0,-6.0,UA,N569UA,883,LGA,DEN,243.0,1620,6.0,46.0
29,2013,1,1,646.0,1.0,1023.0,-7.0,UA,N38727,1496,EWR,SNA,380.0,2434,6.0,46.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,2013,1,1,1707.0,2.0,1928.0,-12.0,DL,N3730B,2121,EWR,ATL,121.0,746,17.0,7.0
302,2013,1,1,1707.0,7.0,2006.0,6.0,UA,N543UA,342,EWR,LAX,334.0,2454,17.0,7.0
303,2013,1,1,1712.0,-7.0,1939.0,-19.0,UA,N569UA,509,LGA,DEN,241.0,1620,17.0,12.0
304,2013,1,1,1712.0,12.0,2042.0,6.0,UA,N485UA,635,EWR,SAT,242.0,1569,17.0,12.0
305,2013,1,1,1714.0,-6.0,1915.0,0.0,AA,N3CVAA,1351,JFK,ORD,146.0,740,17.0,14.0
306,2013,1,1,1716.0,7.0,1902.0,16.0,UA,N19130,1623,EWR,ORD,143.0,719,17.0,16.0
307,2013,1,1,1717.0,-3.0,1920.0,10.0,AA,N539AA,345,LGA,ORD,141.0,733,17.0,17.0
308,2013,1,1,1720.0,-5.0,2121.0,16.0,DL,N723TW,513,JFK,LAX,363.0,2475,17.0,20.0
309,2013,1,1,1725.0,-5.0,1929.0,3.0,US,N680AW,449,EWR,CLT,104.0,529,17.0,25.0
310,2013,1,1,1725.0,5.0,2045.0,24.0,UA,N17122,1712,EWR,IAH,235.0,1400,17.0,25.0
311,2013,1,1,1726.0,-4.0,2054.0,4.0,AA,N386AA,543,JFK,MIA,157.0,1089,17.0,26.0
312,2013,1,1,1726.0,-3.0,2042.0,-18.0,UA,N557UA,512,JFK,SFO,347.0,2586,17.0,26.0
313,2013,1,1,1727.0,2.0,2043.0,3.0,AA,N377AA,145,JFK,SAN,357.0,2446,17.0,27.0
314,2013,1,1,1729.0,11.0,2052.0,-3.0,UA,N14120,1284,EWR,SFO,360.0,2565,17.0,29.0
315,2013,1,1,1730.0,1.0,2039.0,-19.0,UA,N77296,1715,EWR,SEA,344.0,2402,17.0,30.0
316,2013,1,1,1739.0,-6.0,1956.0,3.0,DL,N965DL,2331,LGA,DTW,93.0,502,17.0,39.0
317,2013,1,1,1739.0,-1.0,2051.0,-21.0,DL,N3761R,1339,JFK,PDX,341.0,2454,17.0,39.0
318,2013,1,1,1740.0,70.0,2102.0,68.0,DL,N369NW,2139,LGA,MIA,167.0,1096,17.0,40.0
319,2013,1,1,1742.0,-4.0,2028.0,-24.0,DL,N933DL,1585,LGA,MCO,145.0,950,17.0,42.0
320,2013,1,1,1744.0,-1.0,2055.0,-4.0,DL,N900DE,1935,LGA,TPA,160.0,1010,17.0,44.0
321,2013,1,1,1750.0,0.0,2109.0,-6.0,UA,N525UA,535,JFK,LAX,345.0,2475,17.0,50.0
322,2013,1,1,1756.0,31.0,2036.0,17.0,UA,N523UA,376,EWR,MCO,140.0,937,17.0,56.0
323,2013,1,1,1757.0,-2.0,2027.0,-15.0,DL,N643DL,1047,LGA,ATL,125.0,762,17.0,57.0
324,2013,1,1,1758.0,9.0,2020.0,37.0,UA,N37274,1676,EWR,ORD,135.0,719,17.0,58.0
325,2013,1,1,1800.0,0.0,1951.0,-3.0,UA,N16703,1053,EWR,CLE,83.0,404,18.0,0.0
326,2013,1,1,1802.0,-3.0,1930.0,-14.0,DL,N359NB,1006,LGA,BUF,61.0,292,18.0,2.0
327,2013,1,1,1802.0,1.0,2125.0,-12.0,UA,N75429,1165,EWR,LAX,340.0,2454,18.0,2.0
328,2013,1,1,1803.0,3.0,2021.0,20.0,US,N510UW,373,JFK,CLT,100.0,541,18.0,3.0
329,2013,1,1,1805.0,8.0,2117.0,-2.0,UA,N39463,1152,EWR,PDX,336.0,2434,18.0,5.0
330,2013,1,1,1807.0,29.0,2251.0,NaN,UA,N31412,1228,EWR,SAN,NaN,2425,18.0,7.0

In [72]:
dt.dropna()

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
0,2013,1,1,517.0,2.0,830.0,11.0,UA,N14228,1545,EWR,IAH,227.0,1400,5.0,17.0
1,2013,1,1,533.0,4.0,850.0,20.0,UA,N24211,1714,LGA,IAH,227.0,1416,5.0,33.0
2,2013,1,1,542.0,2.0,923.0,33.0,AA,N619AA,1141,JFK,MIA,160.0,1089,5.0,42.0
3,2013,1,1,554.0,-6.0,812.0,-25.0,DL,N668DN,461,LGA,ATL,116.0,762,5.0,54.0
4,2013,1,1,554.0,-4.0,740.0,12.0,UA,N39463,1696,EWR,ORD,150.0,719,5.0,54.0
5,2013,1,1,558.0,-2.0,753.0,8.0,AA,N3ALAA,301,LGA,ORD,138.0,733,5.0,58.0
6,2013,1,1,558.0,-2.0,924.0,7.0,UA,N29129,194,JFK,LAX,345.0,2475,5.0,58.0
7,2013,1,1,558.0,-2.0,923.0,-14.0,UA,N53441,1124,EWR,SFO,361.0,2565,5.0,58.0
8,2013,1,1,559.0,-1.0,941.0,31.0,AA,N3DUAA,707,LGA,DFW,257.0,1389,5.0,59.0
9,2013,1,1,559.0,-1.0,854.0,-8.0,UA,N76515,1187,EWR,LAS,337.0,2227,5.0,59.0
10,2013,1,1,602.0,-8.0,812.0,-8.0,DL,N971DL,1919,LGA,MSP,170.0,1020,6.0,2.0
11,2013,1,1,606.0,-4.0,858.0,-12.0,AA,N633AA,1895,EWR,MIA,152.0,1085,6.0,6.0
12,2013,1,1,606.0,-4.0,837.0,-8.0,DL,N3739P,1743,JFK,ATL,128.0,760,6.0,6.0
13,2013,1,1,607.0,0.0,858.0,-17.0,UA,N53442,1077,EWR,MIA,157.0,1085,6.0,7.0
14,2013,1,1,611.0,11.0,945.0,14.0,UA,N532UA,303,JFK,SFO,366.0,2586,6.0,11.0
15,2013,1,1,615.0,0.0,833.0,-9.0,DL,N326NB,575,EWR,ATL,120.0,746,6.0,15.0
16,2013,1,1,622.0,-8.0,1017.0,3.0,US,N807AW,245,EWR,PHX,342.0,2133,6.0,22.0
17,2013,1,1,623.0,13.0,920.0,5.0,AA,N3EMAA,1837,LGA,MIA,153.0,1096,6.0,23.0
18,2013,1,1,623.0,-4.0,933.0,1.0,UA,N459UA,496,LGA,IAH,229.0,1416,6.0,23.0
19,2013,1,1,627.0,-3.0,1018.0,0.0,US,N535UW,27,JFK,PHX,330.0,2153,6.0,27.0
20,2013,1,1,628.0,-2.0,1137.0,-3.0,AA,N3BAAA,413,JFK,SJU,192.0,1598,6.0,28.0
21,2013,1,1,628.0,-2.0,1016.0,29.0,UA,N33289,1665,EWR,LAX,366.0,2454,6.0,28.0
22,2013,1,1,629.0,-1.0,824.0,14.0,AA,N3CYAA,303,LGA,ORD,140.0,733,6.0,29.0
23,2013,1,1,629.0,-1.0,824.0,-9.0,US,N426US,1019,EWR,CLT,91.0,529,6.0,29.0
24,2013,1,1,635.0,0.0,1028.0,48.0,AA,N3GKAA,711,LGA,DFW,248.0,1389,6.0,35.0
25,2013,1,1,643.0,-3.0,922.0,-18.0,UA,N497UA,556,EWR,PBI,146.0,1023,6.0,43.0
26,2013,1,1,643.0,-2.0,837.0,-11.0,US,N178US,926,EWR,CLT,91.0,529,6.0,43.0
27,2013,1,1,644.0,8.0,931.0,-9.0,UA,N75435,1701,EWR,FLL,151.0,1065,6.0,44.0
28,2013,1,1,646.0,1.0,910.0,-6.0,UA,N569UA,883,LGA,DEN,243.0,1620,6.0,46.0
29,2013,1,1,646.0,1.0,1023.0,-7.0,UA,N38727,1496,EWR,SNA,380.0,2434,6.0,46.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160724,2013,9,30,1951.0,-5.0,2143.0,-20.0,DL,N318US,2131,LGA,DTW,74.0,502,19.0,51.0
160725,2013,9,30,1953.0,-7.0,2119.0,-13.0,UA,N853UA,695,LGA,ORD,107.0,733,19.0,53.0
160726,2013,9,30,1955.0,-5.0,2219.0,-11.0,DL,N992DL,1147,LGA,ATL,99.0,762,19.0,55.0
160727,2013,9,30,1955.0,-5.0,2112.0,-2.0,US,N957UW,2162,LGA,BOS,35.0,184,19.0,55.0
160728,2013,9,30,1956.0,91.0,2208.0,47.0,DL,N3772H,1576,JFK,SAN,292.0,2446,19.0,56.0
160729,2013,9,30,2001.0,1.0,2302.0,-26.0,UA,N35260,1651,EWR,SFO,323.0,2565,20.0,1.0
160730,2013,9,30,2003.0,-1.0,2235.0,-39.0,UA,N38473,1224,EWR,LAX,295.0,2454,20.0,3.0
160731,2013,9,30,2008.0,33.0,2322.0,40.0,UA,N816UA,208,EWR,SEA,339.0,2402,20.0,8.0
160732,2013,9,30,2009.0,0.0,2126.0,-3.0,UA,N77258,1049,EWR,BOS,38.0,200,20.0,9.0
160733,2013,9,30,2013.0,13.0,2133.0,13.0,US,N747UW,2195,LGA,DCA,41.0,214,20.0,13.0
160734,2013,9,30,2015.0,0.0,2244.0,-23.0,UA,N17730,1545,EWR,IAH,174.0,1400,20.0,15.0
160735,2013,9,30,2017.0,0.0,2253.0,-27.0,UA,N510UA,771,JFK,LAX,304.0,2475,20.0,17.0
160736,2013,9,30,2021.0,-1.0,2144.0,-16.0,UA,N76503,1464,EWR,CLE,54.0,404,20.0,21.0
160737,2013,9,30,2022.0,-3.0,2127.0,-13.0,AA,N3CUAA,2314,JFK,BOS,37.0,187,20.0,22.0
160738,2013,9,30,2026.0,-2.0,2317.0,-23.0,UA,N31412,1680,EWR,MIA,141.0,1085,20.0,26.0
160739,2013,9,30,2028.0,78.0,2255.0,40.0,AA,N338AA,21,JFK,LAX,294.0,2475,20.0,28.0
160740,2013,9,30,2030.0,-5.0,2324.0,-16.0,UA,N484UA,374,EWR,FLL,141.0,1065,20.0,30.0
160741,2013,9,30,2032.0,-13.0,2147.0,-38.0,AA,N434AA,371,LGA,ORD,105.0,733,20.0,32.0
160742,2013,9,30,2035.0,6.0,2318.0,-19.0,UA,N78524,1039,EWR,AUS,191.0,1504,20.0,35.0
160743,2013,9,30,2041.0,-4.0,2147.0,-21.0,DL,N359NB,985,JFK,BOS,37.0,187,20.0,41.0
160744,2013,9,30,2048.0,-12.0,2147.0,-27.0,US,N722US,2197,LGA,DCA,39.0,214,20.0,48.0
160745,2013,9,30,2050.0,5.0,20.0,-33.0,DL,N396DA,347,JFK,SJU,188.0,1598,20.0,50.0
160746,2013,9,30,2052.0,-7.0,2315.0,-43.0,UA,N68453,1416,EWR,MCO,123.0,937,20.0,52.0
160747,2013,9,30,2055.0,-4.0,2158.0,-13.0,UA,N16701,1066,EWR,BOS,40.0,200,20.0,55.0
160748,2013,9,30,2057.0,-3.0,2149.0,-22.0,US,N953UW,2164,LGA,BOS,35.0,184,20.0,57.0
160749,2013,9,30,2105.0,-1.0,2329.0,-25.0,UA,N477UA,475,EWR,IAH,175.0,1400,21.0,5.0
160750,2013,9,30,2121.0,21.0,2349.0,-25.0,DL,N193DN,2363,JFK,LAX,296.0,2475,21.0,21.0
160751,2013,9,30,2140.0,0.0,10.0,-30.0,AA,N335AA,185,JFK,LAX,298.0,2475,21.0,40.0
160752,2013,9,30,2149.0,-7.0,2245.0,-23.0,UA,N813UA,523,EWR,BOS,37.0,200,21.0,49.0
160753,2013,9,30,2233.0,80.0,112.0,42.0,UA,N578UA,471,EWR,SFO,318.0,2565,22.0,33.0

In [76]:
dt[dt.isnull().any(axis=1)].head

<bound method NDFrame.head of         year  month  day  dep_time  dep_delay  arr_time  arr_delay carrier  \
330     2013      1    1    1807.0       29.0    2251.0        NaN      UA
403     2013      1    1       NaN        NaN       NaN        NaN      AA
404     2013      1    1       NaN        NaN       NaN        NaN      AA
855     2013      1    2    2145.0       16.0       NaN        NaN      UA
858     2013      1    2       NaN        NaN       NaN        NaN      AA
859     2013      1    2       NaN        NaN       NaN        NaN      AA
860     2013      1    2       NaN        NaN       NaN        NaN      UA
1067    2013      1    3    1348.0       -2.0    1821.0        NaN      DL
1275    2013      1    3       NaN        NaN       NaN        NaN      AA
1276    2013      1    3       NaN        NaN       NaN        NaN      AA
1277    2013      1    3       NaN        NaN       NaN        NaN      AA
1278    2013      1    3       NaN        NaN       NaN        NaN      AA
1279    2013      1    3       NaN        NaN       NaN        NaN      AA
1280    2013      1    3       NaN        NaN       NaN        NaN      AA
1281    2013      1    3       NaN        NaN       NaN        NaN      UA
1282    2013      1    3       NaN        NaN       NaN        NaN      UA
1700    2013      1    4       NaN        NaN       NaN        NaN      AA
1701    2013      1    4       NaN        NaN       NaN        NaN      AA
1702    2013      1    4       NaN        NaN       NaN        NaN      AA
1703    2013      1    4       NaN        NaN       NaN        NaN      AA
2035    2013      1    5       NaN        NaN       NaN        NaN      AA
2852    2013      1    7       NaN        NaN       NaN        NaN      AA
2853    2013      1    7       NaN        NaN       NaN        NaN      AA
3019    2013      1    8    1119.0       -2.0    1521.0        NaN      UA
3282    2013      1    8       NaN        NaN       NaN        NaN      AA
3283    2013      1    8       NaN        NaN       NaN        NaN      US
3713    2013      1    9       NaN        NaN       NaN        NaN      AA
3714    2013      1    9       NaN        NaN       NaN        NaN      AA
3715    2013      1    9       NaN        NaN       NaN        NaN      AA
3716    2013      1    9       NaN        NaN       NaN        NaN      UA
...      ...    ...  ...       ...        ...       ...        ...     ...
155989  2013      9   19       NaN        NaN       NaN        NaN      UA
156056  2013      9   20     752.0       11.0    1538.0        NaN      UA
156451  2013      9   20       NaN        NaN       NaN        NaN      AA
156452  2013      9   20       NaN        NaN       NaN        NaN      AA
156453  2013      9   20       NaN        NaN       NaN        NaN      UA
156791  2013      9   21       NaN        NaN       NaN        NaN      US
156792  2013      9   21       NaN        NaN       NaN        NaN      UA
156850  2013      9   22     755.0       -4.0    1428.0        NaN      AA
157029  2013      9   22    1514.0        3.0    2000.0        NaN      UA
157208  2013      9   22       NaN        NaN       NaN        NaN      US
157209  2013      9   22       NaN        NaN       NaN        NaN      US
157668  2013      9   23       NaN        NaN       NaN        NaN      US
157669  2013      9   23       NaN        NaN       NaN        NaN      UA
157751  2013      9   24     800.0        0.0       NaN        NaN      UA
158115  2013      9   24       NaN        NaN       NaN        NaN      AA
158415  2013      9   25    1552.0       -7.0    2048.0        NaN      UA
158566  2013      9   25    2052.0        7.0     332.0        NaN      DL
158576  2013      9   25       NaN        NaN       NaN        NaN      US
158577  2013      9   25       NaN        NaN       NaN        NaN      US
158809  2013      9   26    1331.0        2.0    1923.0        NaN      UA
159048  2013      9   26       NaN        NaN       NaN        NaN      US
159278  2013      9   27    1332.0        3.0    1629.0        NaN      AA
159518  2013      9   27       NaN        NaN       NaN        NaN      AA
159519  2013      9   27       NaN        NaN       NaN        NaN      US
159520  2013      9   27       NaN        NaN       NaN        NaN      UA
159681  2013      9   28    1214.0      -11.0    1801.0        NaN      AA
159854  2013      9   28       NaN        NaN       NaN        NaN      AA
159855  2013      9   28       NaN        NaN       NaN        NaN      US
160185  2013      9   29    1734.0       23.0    2159.0        NaN      UA
160286  2013      9   29       NaN        NaN       NaN        NaN      UA

       tailnum  flight origin dest  air_time  distance  hour  minute
330     N31412    1228    EWR  SAN       NaN      2425  18.0     7.0
403     N3EHAA     791    LGA  DFW       NaN      1389   NaN     NaN
404     N3EVAA    1925    LGA  MIA       NaN      1096   NaN     NaN
855     N12221    1299    EWR  RSW       NaN      1068  21.0    45.0
858        NaN     133    JFK  LAX       NaN      2475   NaN     NaN
859     N3FBAA     753    LGA  DFW       NaN      1389   NaN     NaN
860        NaN     623    EWR  ORD       NaN       719   NaN     NaN
1067    N324NB    1705    LGA  MSY       NaN      1183  13.0    48.0
1275    N487AA     321    LGA  ORD       NaN       733   NaN     NaN
1276    N3AMAA     327    LGA  ORD       NaN       733   NaN     NaN
1277    N3GXAA     717    LGA  DFW       NaN      1389   NaN     NaN
1278    N201AA     721    LGA  DFW       NaN      1389   NaN     NaN
1279    N3FVAA     731    LGA  DFW       NaN      1389   NaN     NaN
1280    N573AA    1757    LGA  STL       NaN       888   NaN     NaN
1281       NaN     714    EWR  MIA       NaN      1085   NaN     NaN
1282       NaN     719    EWR  DFW       NaN      1372   NaN     NaN
1700    N541AA     721    LGA  DFW       NaN      1389   NaN     NaN
1701    N3BGAA     745    LGA  DFW       NaN      1389   NaN     NaN
1702    N200AA     883    EWR  DFW       NaN      1372   NaN     NaN
1703    N569AA    2223    LGA  STL       NaN       888   NaN     NaN
2035    N544AA     883    EWR  DFW       NaN      1372   NaN     NaN
2852    N3CYAA     301    LGA  ORD       NaN       733   NaN     NaN
2853    N474AA    1757    LGA  STL       NaN       888   NaN     NaN
3019    N26208    1493    EWR  DEN       NaN      1605  11.0    19.0
3282    N484AA    1855    LGA  STL       NaN       888   NaN     NaN
3283       NaN     123    EWR  CLT       NaN       529   NaN     NaN
3713    N3BVAA     739    LGA  DFW       NaN      1389   NaN     NaN
3714    N3BWAA     759    LGA  DFW       NaN      1389   NaN     NaN
3715    N466AA    1855    LGA  STL       NaN       888   NaN     NaN
3716       NaN     421    LGA  IAH       NaN      1416   NaN     NaN
...        ...     ...    ...  ...       ...       ...   ...     ...
155989     NaN     685    LGA  ORD       NaN       733   NaN     NaN
156056  N38268    1591    EWR  IAH       NaN      1400   7.0    52.0
156451  N425AA     301    LGA  ORD       NaN       733   NaN     NaN
156452  N4XDAA     317    LGA  ORD       NaN       733   NaN     NaN
156453     NaN     687    LGA  ORD       NaN       733   NaN     NaN
156791     NaN     581    EWR  CLT       NaN       529   NaN     NaN
156792     NaN     330    EWR  BOS       NaN       200   NaN     NaN
156850  N584AA     307    LGA  ORD       NaN       733   7.0    55.0
157029  N515UA     745    LGA  DEN       NaN      1620  15.0    14.0
157208     NaN     565    EWR  CLT       NaN       529   NaN     NaN
157209     NaN    2154    LGA  BOS       NaN       184   NaN     NaN
157668     NaN    2148    LGA  BOS       NaN       184   NaN     NaN
157669     NaN     691    LGA  ORD       NaN       733   NaN     NaN
157751  N827UA     544    LGA  ORD       NaN       733   8.0     0.0
158115  N4XUAA     345    LGA  ORD       NaN       733   NaN     NaN
158415  N408UA     375    EWR  SEA       NaN      2402  15.0    52.0
158566  N3731T     347    JFK  SJU       NaN      1598  20.0    52.0
158576     NaN    2148    LGA  BOS       NaN       184   NaN     NaN
158577     NaN    2160    LGA  BOS       NaN       184   NaN     NaN
158809  N67052      15    EWR  HNL       NaN      4963  13.0    31.0
159048     NaN    2183    LGA  DCA       NaN       214   NaN     NaN
159278  N565AA     331    LGA  ORD       NaN       733  13.0    32.0
159518  N584AA     301    LGA  ORD       NaN       733   NaN     NaN
159519     NaN    2164    LGA  BOS       NaN       184   NaN     NaN
159520     NaN     269    LGA  ORD       NaN       733   NaN     NaN
159681  N488AA     300    EWR  DFW       NaN      1372  12.0    14.0
159854  N320AA       1    JFK  LAX       NaN      2475   NaN     NaN
159855     NaN     581    EWR  CLT       NaN       529   NaN     NaN
160185  N463UA     327    EWR  PDX       NaN      2434  17.0    34.0
160286     NaN     331    LGA  ORD       NaN       733   NaN     NaN

[2827 rows x 16 columns]>

In [74]:
dt.shape

(160754, 16)

In [77]:
mdt=dt.dropna()

In [78]:
mdt.shape

(157927, 16)

In [79]:
mdt=dt.dropna(how='all')

In [80]:
mdt.shape

(160754, 16)

In [81]:
mdt=dt.dropna(axis=1)

In [82]:
mdt.columns

Index(['year', 'month', 'day', 'carrier', 'flight', 'origin', 'dest',
       'distance'],
      dtype='object')

In [83]:
mdt.shape

(160754, 8)

In [84]:
dtm=dt.isnull()

In [86]:
dtm.head(331)

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
302,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
303,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
304,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
305,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
306,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
307,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
308,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
309,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
310,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
311,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
312,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
313,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
314,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
315,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
316,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
317,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
318,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
319,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
320,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
321,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
322,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
323,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
324,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
325,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
326,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
327,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
328,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
329,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
330,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False

In [87]:
mdt=dt.fillna(dt.mean())

In [88]:
mdt.head(331)

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
0,2013,1,1,517.0,2.0,830.0,11.000000,UA,N14228,1545,EWR,IAH,227.000000,1400,5.0,17.0
1,2013,1,1,533.0,4.0,850.0,20.000000,UA,N24211,1714,LGA,IAH,227.000000,1416,5.0,33.0
2,2013,1,1,542.0,2.0,923.0,33.000000,AA,N619AA,1141,JFK,MIA,160.000000,1089,5.0,42.0
3,2013,1,1,554.0,-6.0,812.0,-25.000000,DL,N668DN,461,LGA,ATL,116.000000,762,5.0,54.0
4,2013,1,1,554.0,-4.0,740.0,12.000000,UA,N39463,1696,EWR,ORD,150.000000,719,5.0,54.0
5,2013,1,1,558.0,-2.0,753.0,8.000000,AA,N3ALAA,301,LGA,ORD,138.000000,733,5.0,58.0
6,2013,1,1,558.0,-2.0,924.0,7.000000,UA,N29129,194,JFK,LAX,345.000000,2475,5.0,58.0
7,2013,1,1,558.0,-2.0,923.0,-14.000000,UA,N53441,1124,EWR,SFO,361.000000,2565,5.0,58.0
8,2013,1,1,559.0,-1.0,941.0,31.000000,AA,N3DUAA,707,LGA,DFW,257.000000,1389,5.0,59.0
9,2013,1,1,559.0,-1.0,854.0,-8.000000,UA,N76515,1187,EWR,LAS,337.000000,2227,5.0,59.0
10,2013,1,1,602.0,-8.0,812.0,-8.000000,DL,N971DL,1919,LGA,MSP,170.000000,1020,6.0,2.0
11,2013,1,1,606.0,-4.0,858.0,-12.000000,AA,N633AA,1895,EWR,MIA,152.000000,1085,6.0,6.0
12,2013,1,1,606.0,-4.0,837.0,-8.000000,DL,N3739P,1743,JFK,ATL,128.000000,760,6.0,6.0
13,2013,1,1,607.0,0.0,858.0,-17.000000,UA,N53442,1077,EWR,MIA,157.000000,1085,6.0,7.0
14,2013,1,1,611.0,11.0,945.0,14.000000,UA,N532UA,303,JFK,SFO,366.000000,2586,6.0,11.0
15,2013,1,1,615.0,0.0,833.0,-9.000000,DL,N326NB,575,EWR,ATL,120.000000,746,6.0,15.0
16,2013,1,1,622.0,-8.0,1017.0,3.000000,US,N807AW,245,EWR,PHX,342.000000,2133,6.0,22.0
17,2013,1,1,623.0,13.0,920.0,5.000000,AA,N3EMAA,1837,LGA,MIA,153.000000,1096,6.0,23.0
18,2013,1,1,623.0,-4.0,933.0,1.000000,UA,N459UA,496,LGA,IAH,229.000000,1416,6.0,23.0
19,2013,1,1,627.0,-3.0,1018.0,0.000000,US,N535UW,27,JFK,PHX,330.000000,2153,6.0,27.0
20,2013,1,1,628.0,-2.0,1137.0,-3.000000,AA,N3BAAA,413,JFK,SJU,192.000000,1598,6.0,28.0
21,2013,1,1,628.0,-2.0,1016.0,29.000000,UA,N33289,1665,EWR,LAX,366.000000,2454,6.0,28.0
22,2013,1,1,629.0,-1.0,824.0,14.000000,AA,N3CYAA,303,LGA,ORD,140.000000,733,6.0,29.0
23,2013,1,1,629.0,-1.0,824.0,-9.000000,US,N426US,1019,EWR,CLT,91.000000,529,6.0,29.0
24,2013,1,1,635.0,0.0,1028.0,48.000000,AA,N3GKAA,711,LGA,DFW,248.000000,1389,6.0,35.0
25,2013,1,1,643.0,-3.0,922.0,-18.000000,UA,N497UA,556,EWR,PBI,146.000000,1023,6.0,43.0
26,2013,1,1,643.0,-2.0,837.0,-11.000000,US,N178US,926,EWR,CLT,91.000000,529,6.0,43.0
27,2013,1,1,644.0,8.0,931.0,-9.000000,UA,N75435,1701,EWR,FLL,151.000000,1065,6.0,44.0
28,2013,1,1,646.0,1.0,910.0,-6.000000,UA,N569UA,883,LGA,DEN,243.000000,1620,6.0,46.0
29,2013,1,1,646.0,1.0,1023.0,-7.000000,UA,N38727,1496,EWR,SNA,380.000000,2434,6.0,46.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,2013,1,1,1707.0,2.0,1928.0,-12.000000,DL,N3730B,2121,EWR,ATL,121.000000,746,17.0,7.0
302,2013,1,1,1707.0,7.0,2006.0,6.000000,UA,N543UA,342,EWR,LAX,334.000000,2454,17.0,7.0
303,2013,1,1,1712.0,-7.0,1939.0,-19.000000,UA,N569UA,509,LGA,DEN,241.000000,1620,17.0,12.0
304,2013,1,1,1712.0,12.0,2042.0,6.000000,UA,N485UA,635,EWR,SAT,242.000000,1569,17.0,12.0
305,2013,1,1,1714.0,-6.0,1915.0,0.000000,AA,N3CVAA,1351,JFK,ORD,146.000000,740,17.0,14.0
306,2013,1,1,1716.0,7.0,1902.0,16.000000,UA,N19130,1623,EWR,ORD,143.000000,719,17.0,16.0
307,2013,1,1,1717.0,-3.0,1920.0,10.000000,AA,N539AA,345,LGA,ORD,141.000000,733,17.0,17.0
308,2013,1,1,1720.0,-5.0,2121.0,16.000000,DL,N723TW,513,JFK,LAX,363.000000,2475,17.0,20.0
309,2013,1,1,1725.0,-5.0,1929.0,3.000000,US,N680AW,449,EWR,CLT,104.000000,529,17.0,25.0
310,2013,1,1,1725.0,5.0,2045.0,24.000000,UA,N17122,1712,EWR,IAH,235.000000,1400,17.0,25.0
311,2013,1,1,1726.0,-4.0,2054.0,4.000000,AA,N386AA,543,JFK,MIA,157.000000,1089,17.0,26.0
312,2013,1,1,1726.0,-3.0,2042.0,-18.000000,UA,N557UA,512,JFK,SFO,347.000000,2586,17.0,26.0
313,2013,1,1,1727.0,2.0,2043.0,3.000000,AA,N377AA,145,JFK,SAN,357.000000,2446,17.0,27.0
314,2013,1,1,1729.0,11.0,2052.0,-3.000000,UA,N14120,1284,EWR,SFO,360.000000,2565,17.0,29.0
315,2013,1,1,1730.0,1.0,2039.0,-19.000000,UA,N77296,1715,EWR,SEA,344.000000,2402,17.0,30.0
316,2013,1,1,1739.0,-6.0,1956.0,3.000000,DL,N965DL,2331,LGA,DTW,93.000000,502,17.0,39.0
317,2013,1,1,1739.0,-1.0,2051.0,-21.000000,DL,N3761R,1339,JFK,PDX,341.000000,2454,17.0,39.0
318,2013,1,1,1740.0,70.0,2102.0,68.000000,DL,N369NW,2139,LGA,MIA,167.000000,1096,17.0,40.0
319,2013,1,1,1742.0,-4.0,2028.0,-24.000000,DL,N933DL,1585,LGA,MCO,145.000000,950,17.0,42.0
320,2013,1,1,1744.0,-1.0,2055.0,-4.000000,DL,N900DE,1935,LGA,TPA,160.000000,1010,17.0,44.0
321,2013,1,1,1750.0,0.0,2109.0,-6.000000,UA,N525UA,535,JFK,LAX,345.000000,2475,17.0,50.0
322,2013,1,1,1756.0,31.0,2036.0,17.000000,UA,N523UA,376,EWR,MCO,140.000000,937,17.0,56.0
323,2013,1,1,1757.0,-2.0,2027.0,-15.000000,DL,N643DL,1047,LGA,ATL,125.000000,762,17.0,57.0
324,2013,1,1,1758.0,9.0,2020.0,37.000000,UA,N37274,1676,EWR,ORD,135.000000,719,17.0,58.0
325,2013,1,1,1800.0,0.0,1951.0,-3.000000,UA,N16703,1053,EWR,CLE,83.000000,404,18.0,0.0
326,2013,1,1,1802.0,-3.0,1930.0,-14.000000,DL,N359NB,1006,LGA,BUF,61.000000,292,18.0,2.0
327,2013,1,1,1802.0,1.0,2125.0,-12.000000,UA,N75429,1165,EWR,LAX,340.000000,2454,18.0,2.0
328,2013,1,1,1803.0,3.0,2021.0,20.000000,US,N510UW,373,JFK,CLT,100.000000,541,18.0,3.0
329,2013,1,1,1805.0,8.0,2117.0,-2.000000,UA,N39463,1152,EWR,PDX,336.000000,2434,18.0,5.0
330,2013,1,1,1807.0,29.0,2251.0,2.094537,UA,N31412,1228,EWR,SAN,180.685158,2425,18.0,7.0